services:
  database:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
    healthcheck:
      test: psql -U admin -q -d admin -c "SELECT 'ready';" 
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  db-data:


# Enter postgres inside container:
# docker-compose exec database /bin/bash
# Connect:
# psql -U admin -q -d admin
# List tables:
# \dt

# docker-compose up -d --wait